name: yuki-iptv-unofficial
summary: S
description: |
  D
version: '0.0.17'
grade: stable
confinement: strict
base: core22
icon: snap/gui/icon.svg

architectures:
  - build-on: [amd64]
  - build-on: [arm64]

parts:

  python-deps:
    plugin: python
    source: .
    stage-packages:
      - python3
      - python3-gi
      - python3-chardet
      - python3-requests
    python-packages:
      - PyQt6 == 6.7.1
      - yt-dlp == 2024.12.6
    override-build: |
      craftctl default
      # removing qt libs and using the runtime ones instead
      rm -rf $SNAPCRAFT_PART_INSTALL/lib/python3.10/site-packages/PyQt6/Qt6

  yuki:
    plugin: dump
    source: https://codeberg.org/liya/yuki-iptv/releases/download/0.0.17/yuki-iptv_0.0.17_all.deb
    stage-packages:
      - ffmpeg
      - libmpv1
    override-build: |
      craftctl default
      sed -i "s/ctypes.util.find_library('mpv')/'libmpv.so.1'/g" $SNAPCRAFT_PART_INSTALL/usr/lib/yuki-iptv/thirdparty/mpv.py
    after:
      - python-deps


apps:
  yuki-iptv-unofficial:
    command: usr/bin/yuki-iptv
    desktop: usr/share/applications/yuki-iptv.desktop
    extensions:
      - kde-neon-6
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $SNAP/usr/lib/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - home
      - removable-media
      - screen-inhibit-control
    slots:
      - mpris-player

plugs:
  shared-memory:
    private: true

slots:
  mpris-player:
    interface: mpris
    name: yuki_iptv

